name: Test

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        go-version:
          - 1.25.x
          - 1.26.0-rc.1
        os:
          - ubuntu-slim
          - macos-26

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Install Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ matrix.go-version }}
        check-latest: true

    - name: Test
      run: go test -tags=testcgo -v -race -count=1 -shuffle=on -run=. ./...
